import type { Patient, MedicalRecord, Appointment } from './types'

// Realistic mock data with Latin names
export const mockPatients: Patient[] = [
  {
    id: '1',
    expediente: 'EXP-2024-001',
    nombre: 'María',
    apellido: 'González Rodríguez',
    edad: 34,
    genero: 'femenino',
    fechaNacimiento: '1990-03-15',
    telefono: '+52 55 1234 5678',
    email: 'maria.gonzalez@email.com',
    direccion: 'Av. Reforma 234, Col. Centro, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-01-10',
    ultimaVisita: '2024-03-28',
  },
  {
    id: '2',
    expediente: 'EXP-2024-002',
    nombre: 'Carlos',
    apellido: 'Hernández López',
    edad: 45,
    genero: 'masculino',
    fechaNacimiento: '1979-07-22',
    telefono: '+52 55 2345 6789',
    email: 'carlos.hernandez@email.com',
    direccion: 'Calle Insurgentes 567, Col. Roma, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-01-15',
    ultimaVisita: '2024-04-01',
  },
  {
    id: '3',
    expediente: 'EXP-2024-003',
    nombre: 'Ana',
    apellido: 'Martínez Sánchez',
    edad: 28,
    genero: 'femenino',
    fechaNacimiento: '1996-11-08',
    telefono: '+52 55 3456 7890',
    email: 'ana.martinez@email.com',
    direccion: 'Blvd. Ávila Camacho 890, Col. Polanco, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-02-01',
    ultimaVisita: '2024-03-15',
  },
  {
    id: '4',
    expediente: 'EXP-2024-004',
    nombre: 'Roberto',
    apellido: 'García Morales',
    edad: 52,
    genero: 'masculino',
    fechaNacimiento: '1972-05-30',
    telefono: '+52 55 4567 8901',
    email: 'roberto.garcia@email.com',
    direccion: 'Paseo de la Reforma 1234, Col. Juárez, CDMX',
    estado: 'inactivo',
    fechaRegistro: '2024-02-10',
    ultimaVisita: '2024-02-25',
  },
  {
    id: '5',
    expediente: 'EXP-2024-005',
    nombre: 'Laura',
    apellido: 'Ramírez Torres',
    edad: 41,
    genero: 'femenino',
    fechaNacimiento: '1983-09-12',
    telefono: '+52 55 5678 9012',
    email: 'laura.ramirez@email.com',
    direccion: 'Av. Universidad 456, Col. Del Valle, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-02-20',
    ultimaVisita: '2024-04-05',
  },
  {
    id: '6',
    expediente: 'EXP-2024-006',
    nombre: 'Fernando',
    apellido: 'Díaz Vargas',
    edad: 38,
    genero: 'masculino',
    fechaNacimiento: '1986-12-03',
    telefono: '+52 55 6789 0123',
    email: 'fernando.diaz@email.com',
    direccion: 'Calle Madero 789, Col. Centro Histórico, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-03-01',
    ultimaVisita: '2024-04-08',
  },
  {
    id: '7',
    expediente: 'EXP-2024-007',
    nombre: 'Patricia',
    apellido: 'Mendoza Cruz',
    edad: 29,
    genero: 'femenino',
    fechaNacimiento: '1995-04-18',
    telefono: '+52 55 7890 1234',
    email: 'patricia.mendoza@email.com',
    direccion: 'Av. Chapultepec 321, Col. Condesa, CDMX',
    estado: 'alta',
    fechaRegistro: '2024-03-05',
    ultimaVisita: '2024-03-20',
  },
  {
    id: '8',
    expediente: 'EXP-2024-008',
    nombre: 'Javier',
    apellido: 'Ortega Ruiz',
    edad: 55,
    genero: 'masculino',
    fechaNacimiento: '1969-08-25',
    telefono: '+52 55 8901 2345',
    email: 'javier.ortega@email.com',
    direccion: 'Periférico Sur 567, Col. Pedregal, CDMX',
    estado: 'activo',
    fechaRegistro: '2024-03-10',
    ultimaVisita: '2024-04-10',
  },
]

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: '1',
    patientId: '1',
    fecha: '2024-04-08',
    diagnostico: 'Hipertensión arterial controlada',
    tratamiento: 'Losartán 50mg cada 12 horas. Dieta baja en sodio.',
    notas: 'Paciente responde bien al tratamiento. Mantener seguimiento mensual.',
    medico: 'Dr. Alejandro Vega',
  },
  {
    id: '2',
    patientId: '1',
    fecha: '2024-03-15',
    diagnostico: 'Control rutinario - Hipertensión',
    tratamiento: 'Continuar con Losartán 50mg. Agregar ejercicio cardiovascular.',
    notas: 'Presión arterial estable. Recomendar caminatas de 30 min diarios.',
    medico: 'Dr. Alejandro Vega',
  },
  {
    id: '3',
    patientId: '2',
    fecha: '2024-04-01',
    diagnostico: 'Diabetes Mellitus Tipo 2',
    tratamiento: 'Metformina 850mg con cada comida. Monitoreo de glucosa.',
    notas: 'Niveles de glucosa en ayunas: 145 mg/dL. Ajustar dieta.',
    medico: 'Dra. Carmen Solís',
  },
  {
    id: '4',
    patientId: '3',
    fecha: '2024-03-28',
    diagnostico: 'Gastritis crónica',
    tratamiento: 'Omeprazol 20mg en ayunas. Evitar alimentos irritantes.',
    notas: 'Mejoría notable. Continuar tratamiento por 2 semanas más.',
    medico: 'Dr. Miguel Ángel Reyes',
  },
  {
    id: '5',
    patientId: '5',
    fecha: '2024-04-05',
    diagnostico: 'Lumbalgia mecánica',
    tratamiento: 'Naproxeno 500mg cada 8 horas por 5 días. Fisioterapia.',
    notas: 'Referir a rehabilitación física. Evitar cargar objetos pesados.',
    medico: 'Dr. Alejandro Vega',
  },
  {
    id: '6',
    patientId: '6',
    fecha: '2024-04-08',
    diagnostico: 'Rinitis alérgica estacional',
    tratamiento: 'Loratadina 10mg diario. Spray nasal de fluticasona.',
    notas: 'Síntomas exacerbados por temporada de polen. Evitar exposición.',
    medico: 'Dra. Carmen Solís',
  },
]

const today = new Date().toISOString().split('T')[0]

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    patientName: 'María González Rodríguez',
    fecha: today,
    hora: '09:00',
    motivo: 'Control de presión arterial',
    estado: 'pendiente',
    notas: 'Traer resultados de laboratorio',
    medico: 'Dr. Alejandro Vega',
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Carlos Hernández López',
    fecha: today,
    hora: '10:30',
    motivo: 'Seguimiento de diabetes',
    estado: 'pendiente',
    notas: 'Revisar niveles de HbA1c',
    medico: 'Dra. Carmen Solís',
  },
  {
    id: '3',
    patientId: '5',
    patientName: 'Laura Ramírez Torres',
    fecha: today,
    hora: '11:30',
    motivo: 'Revisión de lumbalgia',
    estado: 'completada',
    notas: 'Evaluar progreso de fisioterapia',
    medico: 'Dr. Alejandro Vega',
  },
  {
    id: '4',
    patientId: '3',
    patientName: 'Ana Martínez Sánchez',
    fecha: today,
    hora: '14:00',
    motivo: 'Control de gastritis',
    estado: 'pendiente',
    notas: '',
    medico: 'Dr. Miguel Ángel Reyes',
  },
  {
    id: '5',
    patientId: '6',
    patientName: 'Fernando Díaz Vargas',
    fecha: today,
    hora: '15:30',
    motivo: 'Consulta general',
    estado: 'cancelada',
    notas: 'Paciente canceló por emergencia familiar',
    medico: 'Dra. Carmen Solís',
  },
  {
    id: '6',
    patientId: '8',
    patientName: 'Javier Ortega Ruiz',
    fecha: today,
    hora: '16:30',
    motivo: 'Chequeo anual',
    estado: 'pendiente',
    notas: 'Solicitar estudios de laboratorio completos',
    medico: 'Dr. Alejandro Vega',
  },
]

// Monthly patient registration data for charts
export const monthlyPatientData = [
  { month: 'Ene', pacientes: 12 },
  { month: 'Feb', pacientes: 18 },
  { month: 'Mar', pacientes: 24 },
  { month: 'Abr', pacientes: 15 },
  { month: 'May', pacientes: 22 },
  { month: 'Jun', pacientes: 28 },
]

// Appointment status data for charts
export const appointmentStatusData = [
  { status: 'Completadas', value: 145, fill: 'var(--color-chart-1)' },
  { status: 'Pendientes', value: 32, fill: 'var(--color-chart-2)' },
  { status: 'Canceladas', value: 18, fill: 'var(--color-chart-4)' },
]
